name: Update Wiki

on:
    push:
        paths:
            - "wiki/**"
        branches: [main]
    pull_request:
        paths:
            - "wiki/**"
        branches: [main]

jobs:
    update-wiki:
        runs-on: ubuntu-latest
        name: Update wiki
        steps:
            - uses: OrlovM/Wiki-Action@v1
              with:
                  path: "docs"
                  token: ${{ secrets.GITHUB_TOKEN }}
